import Head from 'next/head';
import Image from 'next/image';
import Header from '@/src/components/Header';
import Landing from '@/src/components/Landing';
import { PromoContainer } from '@/styles/IndexStyles';
import { GetServerSideProps } from 'next';

export default function Home() {
  return (
    <>
      <Head>
        <title>Apple Redesign | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Landing />
      </main>
      <PromoContainer>
        <div>
          <h1>New Promos</h1>
        </div>
      </PromoContainer>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  return {
    props: {},
  };
};
